#!/bin/bash
# shellcheck disable=SC2155

set -e -u -o pipefail
# set -x

info() {
    printf "\\x1b[32m\\xE2\\x87\\x92 %s\\x1b[0m\\n" "$1"
}

error() {
    printf "\\x1b[97m\\x1b[41m\\x21\\x1b[0m \\x1b[31m%s\\x1b[0m\\n" "$1" 1>&2
    exit 1
}

declare -r long_name="./saxifrage"
declare -r short_name="./sax"
declare -r oses=(linux darwin)
declare -r arches=(amd64)

clean_zip() {
    for os in ${oses[*]}; do
        for arch in ${arches[*]}; do
            local file="./saxifrage-${os}-${arch}.zip"
            if [[ -f $file ]]; then
                rm "$file"
            fi
        done
    done
}

clean_bin() {
    if [[ -f $long_name ]]; then
        rm "$long_name"
    fi
    if [[ -f $short_name ]]; then
        rm "$short_name"
    fi
}

main() {
    clean_bin
    clean_zip

    for os in ${oses[*]}; do
        for arch in ${arches[*]}; do
            info "Creating binary ${short_name} - OS: ${os}, Arch: ${arch}"

            export GOOS=${os}
            export GOARCH=${arch}

            make

            mv $long_name $short_name

            archive="saxifrage-${os}-${arch}.zip"

            info "Creating archive ${archive}"

            zip "$archive" $short_name

            clean_bin
        done
    done
}

main
