name: Saxifrage Checks
on:
  push:
    branches:
      - stable
      - 'release/*'
  pull_request:
    branches:
      - stable
      - 'release/*'
jobs:
  build:
    name: Linting & Testing
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod') }}
      - run: go install golang.org/x/lint/golint
      - run: go install github.com/securego/gosec/cmd/gosec
      - run: go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
      - name: make lint
        run: |
          export PATH=${PATH}:"$(go env GOPATH)/bin"
          make lint
      - run: make test
