name: Saxifrage Checks
on:
  push:
    branches:
      - stable
      - 'release/*'
  pull_request:
    branches:
      - stable
      - 'release/*'
jobs:
  build:
    name: Linting & Testing
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/cache@v3.0.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod') }}
      # - uses: golangci/golangci-lint-action@v2
      #   with:
      #     version: latest
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: go install github.com/securego/gosec/cmd/gosec@latest
      - name: make lint
        run: |
          export PATH=${PATH}:"$(go env GOPATH)/bin"
          make lint
      - run: make test
