name: Saxifrage Checks
on:
  push:
    branches:
      - stable
      - 'release/*'
  pull_request:
    branches:
      - stable
      - 'release/*'
jobs:
  build:
    name: Linting & Testing
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout source code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #v5.0.0
        with:
          go-version: '1.22'

      - name: Run Test Suite
        run: make test
