name: Saxifrage Releases
on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Release & Binaries
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          ref: stable
      - uses: actions/setup-go@v4
        with:
          go-version: '1.16'
      - run: make binaries
      - name: create release
        run: |
          tagname="${GITHUB_REF#refs/tags/}"
          gh release create "$tagname" ./*.zip --target stable --title "$tagname" --notes "Release of version $tagname"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
