name: Saxifrage Releases
on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Release & Binaries
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stable
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - run: go install github.com/markbates/pkger/cmd/pkger
      - run: make binaries
      - uses: actions/create-release@v1.1.1
        id: release-id # to retrieve the release's info during the following step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: "Release of version ${{ github.ref }}"
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release-id.outputs.upload_url }}
          asset_path: ./saxifrage-linux-amd64.zip
          asset_name: saxifrage-linux-amd64.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release-id.outputs.upload_url }}
          asset_path: ./saxifrage-darwin-amd64.zip
          asset_name: saxifrage-darwin-amd64.zip
          asset_content_type: application/zip
