name: Saxifrage Releases
on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Release & Binaries
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout source code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #v5.0.0
        with:
          go-version: '1.22'

      - run: make binaries
      - name: create release
        run: |
          tagname="${GITHUB_REF#refs/tags/}"
          gh release create "$tagname" ./*.zip --target stable --title "$tagname" --notes "Release of version $tagname"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
